### ISSUE TITLE
Flag is doubled

### ISSUE THREAD

**Issue by Bufflak** [Bufflak/FASA-TU#2]
Same for both texture sets, even though Flag mesh is excluded.

![screenshot2](https://user-images.githubusercontent.com/52627231/61584526-652e3480-ab49-11e9-8a96-9fec032d441b.png)

**Comment by shadowmage45** [comment]
Take a look at the model and see what is going on with that transform/mesh.  Look like the mesh itself might be doubled / have two quads in it?

I doubt that issue is being caused by TU, as it doesn't/can't add new meshes.

**Comment by Bufflak** [comment]
Same with just FASA and RPM installed. 
Officially the first bug that's not my fault :)
https://github.com/KSP-RO/FASA-RO/issues/38
