### ISSUE TITLE
FASA_TU_ReflectionsSetup.cfg conflicts

### ISSUE THREAD

**Issue by Bufflak** [Bufflak/FASA-TU#4]
When it' there, old SSTU/PBR/Metallic shaders are being applied to models.
https://github.com/KSP-RO/FASA-RO/blob/master/GameData/FASA/FASA_TU_ReflectionsSetup.cfg

- find a way to disable parts of a cfg with mm
- find a way to switch cfg files with mm
- overwrite the file with a new version, where KSP_MODEL_SHADER isn't defined for a specific part.
  how to restore original, once FASA_TU is uninstalled?
- owerwrite with new version, where all shaders are changed to TU/Metallic
- just delete the damn thing

**Comment by shadowmage45** [comment]
Something like the below should delete specific nodes
````
!KSP_MODEL_SHADER[FASA_Apollo_CM]{}
OR
~KSP_MODEL_SHADER[FASA_Apollo_CM]{}
OR
-KSP_MODEL_SHADER[FASA_Apollo_CM]{}
````
I don't remember which of the syntax works for root nodes... but its one of those :)

The name between the brackets is from this line in each root node: https://github.com/KSP-RO/FASA-RO/blob/master/GameData/FASA/FASA_TU_ReflectionsSetup.cfg#L10
So you'll need one patch line to delete each named KSP_MODEL_SHADER in that file.

**Comment by Bufflak** [comment]
> 
> ```
> !KSP_MODEL_SHADER[FASA_Apollo_CM]{}
works
> 
> ```
> ~KSP_MODEL_SHADER[FASA_Apollo_CM]{}
doesn't work, 1 error while loading MM patches
> 
> ```
> -KSP_MODEL_SHADER[FASA_Apollo_CM]{}
works


Thanks, i'll go with '!'
